#############################################################################################################################
#
#   Build minor-release from develop branch
# 
#   Description
#   This workflow will used to build a new release that can be promoted to Staging/Prod
#
#
name: Create new Release
on:
  workflow_dispatch:
    branches:
    - 'development'
    - 'main'
    inputs:
      release:
        type: string
        description: (optional) Enter new release version => 1.6.2 (leave blank for auto)
jobs:
  #############################################################################################################################
  #
  # Create new release
  #
  # Required inputs:
  # - prefix
  #
  # Outputs:
  # New Release created and published in GitHub
  #

  create-release:
    name: Create new release
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Get new version
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: develop
        custom_tag: ${{ github.event.inputs.release }}

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_version }}
        body: ${{ steps.tag_version.outputs.changelog }}

    - id: diplay-results
      run: "echo ::warning::Create new relase: ${{ steps.tag_version.outputs.new_tag }}"
