name: Create new Release (chatGPT)
on:
  workflow_dispatch:
    branches:
    - 'development'
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract commit messages
        run: |
          git log --first-parent --oneline --decorate --pretty=format:"%s" $(git describe --tags --abbrev=0)..HEAD > commits.txt

      - name: Generate release notes
        run: |
          cat commits.txt | grep -P '^(fix|feat|docs|chore):' > release-notes.txt

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.sha }}
          release_name: Release v${{ github.sha }}
          body: |
            $(cat release-notes.txt)
          draft: false
          prerelease: false
